# Generated by Django 5.2.5 on 2025-09-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quizattempt_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='marks_awarded',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
