# Generated by Django 5.2.5 on 2025-09-22 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.university'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='employee_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('university', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together={('university', 'employee_id')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('student_id', 'university')},
        ),
    ]
