# Generated by Django 5.2.5 on 2025-09-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_university_alter_course_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('university', 'student_id')},
        ),
    ]
