# Generated by Django 5.2.5 on 2025-09-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_student_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentGrade',
        ),
    ]
