# Generated by Django 5.2.5 on 2025-10-16 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_studentgrade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
